# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 580)
        MainWindow.setStyleSheet("#MainWindow{\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.045, y1:0.261, x2:0.988636, y2:0.955, stop:0 rgba(235, 209, 196, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                 "                                 }\n"
                                 "                                 ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
                                         "background-color: qlineargradient(spread:pad, x1:0.045, y1:0.261, x2:0.988636, y2:0.955, stop:0 rgba(235, 209, 196, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                         "                                 }\n"
                                         "                                 ")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 761, 571))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(40, -10, 581, 171))
        self.widget_2.setStyleSheet("#widget_2 {\n"
                                    "border-image: url(images/Crackterize.png) 100 -200 150 100 stretch stretch;\n"
                                    "}")
        self.widget_2.setObjectName("widget_2")
        self.cracktype = QtWidgets.QLabel(self.widget)
        self.cracktype.setGeometry(QtCore.QRect(50, 190, 181, 71))
        self.cracktype.setStyleSheet("#cracktype {\n"
                                     "    font: 700 9pt \"Segoe UI\";\n"
                                     "    font: 700 9pt \"Segoe UI\";\n"
                                     "    font: 600 9pt \"Segoe UI\";\n"
                                     "position: absolute;\n"
                                     "width: 50px;\n"
                                     "height: 50px;\n"
                                     "left: 143px;\n"
                                     "top: 236px;\n"
                                     "\n"
                                     "font-family: \'Franklin Gothic Medium\';\n"
                                     "font-style: normal;\n"
                                     "font-weight: 600;\n"
                                     "font-size: 20px;\n"
                                     "line-height: 42px;\n"
                                     "text-align: center;\n"
                                     "\n"
                                     "color: \n"
                                     "#664323;\n"
                                     "}")
        self.cracktype.setObjectName("cracktype")
        self.crackprogression = QtWidgets.QLabel(self.widget)
        self.crackprogression.setGeometry(QtCore.QRect(50, 250, 201, 31))
        self.crackprogression.setStyleSheet("#crackprogression {\n"
                                            "    font: 700 9pt \"Segoe UI\";\n"
                                            "    font: 700 9pt \"Segoe UI\";\n"
                                            "    font: 600 9pt \"Segoe UI\";\n"
                                            "position: absolute;\n"
                                            "width: 50px;\n"
                                            "height: 50px;\n"
                                            "left: 143px;\n"
                                            "top: 236px;\n"
                                            "\n"
                                            "font-family: \'Franklin Gothic Medium\';\n"
                                            "font-style: normal;\n"
                                            "font-weight: 600;\n"
                                            "font-size: 20px;\n"
                                            "line-height: 42px;\n"
                                            "text-align: center;\n"
                                            "\n"
                                            "color: \n"
                                            "#664323;\n"
                                            "}")
        self.crackprogression.setObjectName("crackprogression")
        self.remarks = QtWidgets.QLabel(self.widget)
        self.remarks.setGeometry(QtCore.QRect(50, 300, 121, 21))
        self.remarks.setStyleSheet("#remarks {\n"
                                   "    font: 700 9pt \"Segoe UI\";\n"
                                   "    font: 700 9pt \"Segoe UI\";\n"
                                   "    font: 600 9pt \"Segoe UI\";\n"
                                   "position: absolute;\n"
                                   "width: 50px;\n"
                                   "height: 50px;\n"
                                   "left: 143px;\n"
                                   "top: 236px;\n"
                                   "\n"
                                   "font-family: \'Franklin Gothic Medium\';\n"
                                   "font-style: normal;\n"
                                   "font-weight: 600;\n"
                                   "font-size: 15px;\n"
                                   "line-height: 42px;\n"
                                   "text-align: center;\n"
                                   "\n"
                                   "color: \n"
                                   "#664323;\n"
                                   "}")
        self.remarks.setObjectName("remarks")
        self.notes = QtWidgets.QTextEdit(self.widget)
        self.notes.setGeometry(QtCore.QRect(50, 330, 661, 161))
        self.notes.setStyleSheet("#notes {\n"
                                 "        border-radius: 10px;\n"
                                 "        font-size: 18px;\n"
                                 "        font-family: Arial;\n"
                                 "        color: #333;\n"
                                 "        background-color: #fff;\n"
                                 "        border: 2px solid #aaa;\n"
                                 "        padding: 10px;\n"
                                 "    }")
        self.notes.setObjectName("notes")
        self.discard = QtWidgets.QPushButton(self.widget)
        self.discard.setGeometry(QtCore.QRect(130, 510, 111, 31))
        self.discard.setStyleSheet("#discard{\n"
                                   " background-color: #6A6E72;\n"
                                   "            color: white;\n"
                                   "font: bold;\n"
                                   "            border-radius: 10px;\n"
                                   "            padding: 10px 20px;\n"
                                   "}")
        self.discard.setObjectName("discard")
        self.save1 = QtWidgets.QPushButton(self.widget)
        self.save1.setGeometry(QtCore.QRect(330, 510, 101, 31))
        self.save1.setStyleSheet("#save1{\n"
                                 " background-color: #6F4B27;\n"
                                 "            color: white;\n"
                                 "font: bold;\n"
                                 "            border-radius: 10px;\n"
                                 "            padding: 10px 20px;\n"
                                 "}")
        self.save1.setObjectName("save1")
        self.print1 = QtWidgets.QPushButton(self.widget)
        self.print1.setGeometry(QtCore.QRect(530, 510, 101, 31))
        self.print1.setStyleSheet("#print1{\n"
                                  " background-color: #2E74A9;\n"
                                  "            color: white;\n"
                                  "font: bold;\n"
                                  "            border-radius: 10px;\n"
                                  "            padding: 10px 20px;\n"
                                  "}")
        self.print1.setObjectName("print1")
        self.combo1 = QtWidgets.QComboBox(self.widget)
        self.combo1.setGeometry(QtCore.QRect(250, 170, 381, 31))
        self.combo1.setStyleSheet("#combo1 {\n"
                                  "        border-radius: 10px;\n"
                                  "        font-size: 18px;\n"
                                  "        font-family: Arial;\n"
                                  "        color: #333;\n"
                                  "        background-color: #fff;\n"
                                  "        border: 2px solid #aaa;\n"
                                  "        padding: 10px;\n"
                                  "    }")
        self.combo1.setObjectName("combo1")
        self.combo1.addItem("item 1")
        self.loccrack = QtWidgets.QLabel(self.widget)
        self.loccrack.setGeometry(QtCore.QRect(50, 160, 181, 51))
        self.loccrack.setStyleSheet("#loccrack {\n"
                                    "    font: 700 9pt \"Franklin Gothic Medium\";\n"
                                    "    font: 600 9pt \"Franklin Gothic Medium\";\n"
                                    "position: absolute;\n"
                                    "width: 50px;\n"
                                    "height: 50px;\n"
                                    "left: 143px;\n"
                                    "top: 236px;\n"
                                    "\n"
                                    "font-family: \'Franklin Gothic Medium\';\n"
                                    "font-style: normal;\n"
                                    "font-weight: 600;\n"
                                    "font-size: 20px;\n"
                                    "line-height: 42px;\n"
                                    "text-align: center;\n"
                                    "\n"
                                    "color: \n"
                                    "#664323;\n"
                                    "}")
        self.loccrack.setObjectName("loccrack")
        self.combo2 = QtWidgets.QComboBox(self.widget)
        self.combo2.setGeometry(QtCore.QRect(250, 210, 381, 31))
        self.combo2.setStyleSheet("#combo2 {\n"
                                  "        border-radius: 10px;\n"
                                  "        font-size: 18px;\n"
                                  "        font-family: Arial;\n"
                                  "        color: #333;\n"
                                  "        background-color: #fff;\n"
                                  "        border: 2px solid #aaa;\n"
                                  "        padding: 10px;\n"
                                  "    }")
        self.combo2.setObjectName("combo2")
        self.combo3 = QtWidgets.QComboBox(self.widget)
        self.combo3.setGeometry(QtCore.QRect(250, 250, 381, 31))
        self.combo3.setStyleSheet("#combo3 {\n"
                                  "        border-radius: 10px;\n"
                                  "        font-size: 18px;\n"
                                  "        font-family: Arial;\n"
                                  "        color: #333;\n"
                                  "        background-color: #fff;\n"
                                  "        border: 2px solid #aaa;\n"
                                  "        padding: 10px;\n"
                                  "    }")
        self.combo3.setObjectName("combo3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cracktype.setText(_translate("MainWindow", "Crack Type:"))
        self.crackprogression.setText(_translate("MainWindow", "Crack Progression:"))
        self.remarks.setText(_translate("MainWindow", "Remarks:"))
        self.discard.setText(_translate("MainWindow", "Discard"))
        self.save1.setText(_translate("MainWindow", "Save"))
        self.print1.setText(_translate("MainWindow", "Print"))
        self.loccrack.setText(_translate("MainWindow", "Location of Crack:"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
