# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose_folder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(346, 334)
        Dialog.setMaximumSize(QtCore.QSize(346, 334))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("#label{\n"
                                 "    font: 900 13pt \"Segoe UI Black\";\n"
                                 "    alignment: center;\n"
                                 "    color: rgba(111, 75, 39, 0.77);\n"
                                 "}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setMinimumSize(QtCore.QSize(310, 210))
        self.scrollArea.setMaximumSize(QtCore.QSize(310, 210))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 308, 208))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Create_new = QtWidgets.QPushButton(self.widget_2)
        self.Create_new.setMinimumSize(QtCore.QSize(0, 35))
        self.Create_new.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Create_new.setStyleSheet("#Create_new{\n"
                                      "font-weight:bold;\n"
                                      "color: white;\n"
                                      "background-color: #6F4B27;\n"
                                      "border-top-left-radius: 7px;\n"
                                      "border-top-right-radius: 7px;\n"
                                      "border-bottom-left-radius: 7px;\n"
                                      "border-bottom-right-radius: 7px;\n"
                                      "font-family: Inter;\n"
                                      "font-size: 11px;\n"
                                      "text-align: center;\n"
                                      "}\n"
                                      "#Create_new:hover{\n"
                                      "color: rgb(144,115,87);\n"
                                      "border : 3px solid rgb(144,115,87);\n"
                                      "background-color: white;\n"
                                      "}\n"
                                      "")
        self.Create_new.setObjectName("Create_new")
        self.horizontalLayout_2.addWidget(self.Create_new)
        self.back = QtWidgets.QPushButton(self.widget_2)
        self.back.setMinimumSize(QtCore.QSize(0, 35))
        self.back.setMaximumSize(QtCore.QSize(16777215, 35))
        self.back.setStyleSheet("#back{\n"
                                "font-weight:bold;\n"
                                "color: white;\n"
                                "background-color: #6F4B27;\n"
                                "border-top-left-radius: 7px;\n"
                                "border-top-right-radius: 7px;\n"
                                "border-bottom-left-radius: 7px;\n"
                                "border-bottom-right-radius: 7px;\n"
                                "font-family: Inter;\n"
                                "font-size: 11px;\n"
                                "text-align: center;\n"
                                "}\n"
                                "#back:hover{\n"
                                "color: rgb(144,115,87);\n"
                                "border : 3px solid rgb(144,115,87);\n"
                                "background-color: white;\n"
                                "}\n"
                                "")
        self.back.setObjectName("back")
        self.horizontalLayout_2.addWidget(self.back)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose an existing project"))
        self.Create_new.setText(_translate("Dialog", "Create New Project"))
        self.back.setText(_translate("Dialog", "Back"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
