# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'holecolumn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class hole(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowFlags(Qt.FramelessWindowHint)
        Dialog.resize(600, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("#widget{\n"

                                  "border-top-left-radius: 10px;\n"
                                  "border-top-right-radius: 10px;\n"
                                  "border-bottom-left-radius: 10px;\n"
                                  "border-bottom-right-radius: 10px;\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setStyleSheet("#label{\n"
                                 "  background-color: transparent;  \n"
                                 "font: 200 15pt Segoe UI Black;\n"
                                 "alignment: center;\n"
                                 "color: rgba(111, 75, 39, 0.77);\n"
                                 "                                 }")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setStyleSheet("#label_2{\n"
                                   "  background-color: transparent;  \n"
                                   "font: 200 15pt Segoe UI Black;\n"
                                   "alignment: center;\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "                                 }")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        self.label_3.setStyleSheet("#label_3{\n"
                                   "  background-color: transparent;  \n"
                                   "font: 200 11pt Arial, Sans Serif;\n"
                                   "alignment: center;\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.Dia_lineEdit = QtWidgets.QLineEdit(self.widget_6)

        self.Dia_lineEdit.setMinimumSize(QtCore.QSize(-50, 0))
        self.Dia_lineEdit.setObjectName("Dia_lineEdit")
        self.horizontalLayout.addWidget(self.Dia_lineEdit)
        self.Dia_comboBox = QtWidgets.QComboBox(self.widget_6)
        self.Dia_comboBox.setObjectName("Dia_comboBox")
        self.Dia_comboBox.addItems(["inches", "feet", "yards", "meters", "centimeters"])
        self.horizontalLayout.addWidget(self.Dia_comboBox)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setStyleSheet("#label_4{\n"
                                   "  background-color: transparent;  \n"
                                   "font: 200 11pt Arial, Sans Serif;\n"
                                   "alignment: center;\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft)
        self.DH_lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.DH_lineEdit.setObjectName("DH_lineEdit")
        self.horizontalLayout_2.addWidget(self.DH_lineEdit)
        self.DH_comboBox = QtWidgets.QComboBox(self.widget_3)
        self.DH_comboBox.setObjectName("DH_comboBox")
        self.DH_comboBox.addItems(["inches", "feet", "yards", "meters", "centimeters"])
        self.horizontalLayout_2.addWidget(self.DH_comboBox)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        self.label_5.setStyleSheet("#label_5{\n"
                                   "  background-color: transparent;  \n"
                                   "font: 200 11pt Arial, Sans Serif;\n"
                                   "alignment: center;\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.Qua_lineEdit = QtWidgets.QLineEdit(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qua_lineEdit.sizePolicy().hasHeightForWidth())
        self.Qua_lineEdit.setSizePolicy(sizePolicy)
        self.Qua_lineEdit.setObjectName("Qua_lineEdit")
        self.horizontalLayout_3.addWidget(self.Qua_lineEdit)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_4.setContentsMargins(27, 7, 27, 7)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.calculateBtn = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculateBtn.sizePolicy().hasHeightForWidth())
        self.calculateBtn.setSizePolicy(sizePolicy)
        self.calculateBtn.setStyleSheet("#calculateBtn{\n"
                                        "font-weight:bold;\n"
                                        "color: white;\n"
                                        "background-color: #6F4B27;\n"
                                        "font-family: Inter;\n"
                                        "border-top-left-radius: 12px;\n"
                                        "border-top-right-radius: 12px;\n"
                                        "border-bottom-left-radius: 12px;\n"
                                        "border-bottom-right-radius: 12px;\n"
                                        "font-size: 15px;\n"
                                        "text-align: center;\n"
                                        "}\n"
                                        "#calculateBtn:hover{\n"
                                        "color: rgb(144,115,87);\n"
                                        "border : 3px solid rgb(144,115,87);\n"
                                        "background-color: white;\n"
                                        "}")
        self.calculateBtn.setObjectName("calculateBtn")
        self.calculateBtn.clicked.connect(self.calculate)
        self.verticalLayout_4.addWidget(self.calculateBtn)
        self.closeBtn = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeBtn.sizePolicy().hasHeightForWidth())
        self.closeBtn.setSizePolicy(sizePolicy)
        self.closeBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.closeBtn.setStyleSheet("#closeBtn{\n"
                                    "font-weight:bold;\n"
                                    "color: white;\n"
                                    "background-color: #6A6E72;\n"
                                    "font-family: Inter;\n"
                                    "border-top-left-radius: 10px;\n"
                                    "border-top-right-radius: 10px;\n"
                                    "border-bottom-left-radius: 10px;\n"
                                    "border-bottom-right-radius: 10px;\n"
                                    "font-size: 15px;\n"
                                    "text-align: center;\n"
                                    "}\n"
                                    "#closeBtn:hover{\n"
                                    "color: #6A6E72;\n"
                                    "border :2px solid #6A6E72;\n"
                                    "background-color: white;\n"
                                    "}")
        self.closeBtn.setObjectName("closeBtn")
        self.closeBtn.clicked.connect(Dialog.close)
        self.verticalLayout_4.addWidget(self.closeBtn)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.result = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result.sizePolicy().hasHeightForWidth())
        self.result.setSizePolicy(sizePolicy)
        self.result.setMinimumSize(QtCore.QSize(0, 0))
        self.result.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.result.setStyleSheet("#result{\n"
                                  "  background-color: transparent;  \n"
                                  "font: 200 12pt Segoe UI Black;\n"
                                  "alignment: center;\n"
                                  "}")
        self.result.setScaledContents(True)
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setWordWrap(True)
        self.result.setObjectName("result")
        self.horizontalLayout_5.addWidget(self.result)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Hole, Column, "))
        self.label_2.setText(_translate("Dialog", "Round Footings Calculator"))
        self.label_3.setText(_translate("Dialog", "Diameter:"))
        self.label_4.setText(_translate("Dialog", "Depth/Height:"))
        self.label_5.setText(_translate("Dialog", "Quantity:"))
        self.calculateBtn.setText(_translate("Dialog", "Calculate"))
        self.closeBtn.setText(_translate("Dialog", "Close"))

    def calculate(self):
        try:
            diameter = float(self.Dia_lineEdit.text())
            depth = float(self.DH_lineEdit.text())
            quantity = int(self.Qua_lineEdit.text())
            diameter_unit = self.Dia_comboBox.currentText()
            depth_unit = self.DH_comboBox.currentText()

            # Convert diameter to inches
            if diameter_unit == "feet":
                diameter *= 12
            elif diameter_unit == "yards":
                diameter *= 36
            elif diameter_unit == "meters":
                diameter *= 39.37
            elif diameter_unit == "centimeters":
                diameter *= 0.3937

            # Convert depth to inches
            if depth_unit == "feet":
                depth *= 12
            elif depth_unit == "yards":
                depth *= 36
            elif depth_unit == "meters":
                depth *= 39.37
            elif depth_unit == "centimeters":
                depth *= 0.3937

            volume = 3.14159 * (diameter / 2) ** 2 * depth * quantity

            result = (
                f"Total volume of concrete needed: \n"
                f"{volume:.2f} cubic inches \n"
                f"{volume / 1728:.2f} cubic feet \n"
                f"{volume / 46656:.2f} cubic yards \n"
                f"{volume / 61023.74:.2f} cubic meters \n"
                f"{volume * 16.387:.2f} cubic centimeters"
            )

            self.result.setText(result)
            self.result.setStyleSheet("font-size: 10pt; font-family: Inter; font-weight: Bold; ")

        except ValueError:
            self.result.setText("Please enter valid input values.")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = hole()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
