# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Homes.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QListView, QComboBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(930, 590)
        MainWindow.setWindowFlag(QtCore.Qt.WindowMaximizeButtonHint, False)
        MainWindow.setMinimumSize(QtCore.QSize(100, 200))
        MainWindow.setMaximumSize(QtCore.QSize(1452, 1024))
        MainWindow.setStyleSheet("#MainWindow{\n"
                                 "background-color: qlineargradient(spread:pad, x1:0.045, y1:0.261, x2:0.988636, y2:0.955, stop:0 rgba(235, 209, 196, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                 "width: fit-content;\n"
                                 "heigth: fit-content;\n"
                                 "block-size: fit-content;\n"
                                 "}\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
                                         "background-color: qlineargradient(spread:pad, x1:0.045, y1:0.261, x2:0.988636, y2:0.955, stop:0 rgba(235, 209, 196, 255), stop:1 rgba(255, 255, 255, 255));\n"
                                         "width: fit-content;\n"
                                         "heigth: fit-content;\n"
                                         "block-size: fit-content;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 931, 601))
        self.widget.setStyleSheet("width: fit-content;\n"
                                  "block-size: fit-content;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.threeBtn = QtWidgets.QWidget(self.widget_2)
        self.threeBtn.setGeometry(QtCore.QRect(180, 60, 531, 61))
        self.threeBtn.setContentsMargins(10, 0, 50, 0)
        effect = QtWidgets.QGraphicsDropShadowEffect()
        effect.setBlurRadius(8)
        self.threeBtn.setGraphicsEffect(effect)
        self.threeBtn.setStyleSheet("#threeBtn{\n"
                                    "background-color: rgb(255, 255, 255);\n"
                                    "border-radius:28px;\n"
                                    "}\n"
                                    "")
        self.threeBtn.setObjectName("threeBtn")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.threeBtn)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.myProjects = QtWidgets.QComboBox(self.threeBtn)

        # edited text allign
        self.myProjects.setMinimumSize(QtCore.QSize(25, 0))
        self.myProjects.setGeometry(200, 150, 150, 30)
        geek_list = ["Project 1", "Project 2", "Project 3", "Project 4"]
        self.myProjects.addItems(geek_list)
        self.myProjects.setEditable(True)
        self.ledit = self.myProjects.lineEdit()
        self.ledit.setReadOnly(True)
        self.ledit.setAlignment(Qt.AlignCenter)
        self.myProjects.setEditText("My Projects")

        def handleSelection(text):
            # change back to default title after item is selected
            self.myProjects.setEditText("My Projects")

        self.myProjects.activated[str].connect(handleSelection)
        # Disable showing the selected item in the title
        view = QListView()
        view.setWordWrap(True)
        self.myProjects.setView(view)
        self.myProjects.setStyleSheet("#myProjects{\n"
                                      "padding-left: 10px;\n"
                                      "border-radius:4px;\n"
                                      "font: 600 12pt \"Segoe UI\";\n"
                                      "color:#4A3B28;\n"
                                      "background: transparent;\n"
                                      "border:0px;"
                                      "text-align: center;\n"
                                      "}\n"

                                      "#myProjects::drop-down{\n"
                                      "image:url(images/arrowdown.png);\n"
                                      "width: 20px;\n"
                                      "height: 20px;\n"
                                      "text-align: center;\n"
                                      "}\n"

                                      "#myProjects QAbstractItemView {\n"
                                      "background-color: rgb(255, 255, 255);\n"
                                      "outline: none;"
                                      "text-align: center;\n"

                                      "border:0px;"
                                      "\n"
                                      "}\n"

                                      "#myProjects QAbstractItemView::item {\n"
                                      "background-color: #F4EBE6;\n"
                                      "color: #4A3B28;\n"
                                      "text-align: center;\n"
                                      "min-height: 35px; min-width: 50px;"
                                      "border:0px;"
                                      "}\n"

                                      "#myProjects QListView{"
                                      "border:0px;"
                                      # "color:rgb(87, 96, 134);"
                                      # "background-color:rgb(255, 255, 255);"
                                      "font-weight:bold;"
                                      # "selection-background-color: rgb(47, 175, 178);"
                                      # "show-decoration-selected: 1;"
                                      "text-align: center;\n"
                                      "}"

                                      "#myProjects QListView::item{"
                                      "border:0px;"
                                      "border-radius: 15px;"
                                      "padding:8px; "
                                      "margin:10px;"
                                      "text-align: center;\n"
                                      "}"
                                      "#myProjects QListView::text {"
                                      "left: 27px;}"

                                      "#myProjects QListView::item:selected { "
                                      "color: white; "
                                      "background-color: #4A3B28}")
        self.myProjects.setObjectName("myProjects")
        self.horizontalLayout.addWidget(self.myProjects)

        self.history = QtWidgets.QComboBox(self.threeBtn)

        # edited text allign
        self.history.setMinimumSize(QtCore.QSize(25, 0))
        self.history.setGeometry(200, 150, 150, 30)
        geek_list = ["Project 1", "Project 2", "Project 3", "Project 4"]
        self.history.addItems(geek_list)
        self.history.setEditable(True)
        self.ledit = self.history.lineEdit()
        self.ledit.setReadOnly(True)
        self.ledit.setAlignment(Qt.AlignCenter)
        self.history.setEditText("History")

        def handleSelection(text):
            # change back to default title after item is selected
            self.history.setEditText("History")

        self.history.activated[str].connect(handleSelection)
        # Disable showing the selected item in the title
        view = QListView()
        view.setWordWrap(True)
        self.history.setView(view)
        self.history.setStyleSheet("#history{\n"
                                   "padding-left: 10px;\n"
                                   "border-radius:4px;\n"
                                   "font: 600 12pt \"Segoe UI\";\n"
                                   "color:#4A3B28;\n"
                                   "background: transparent;\n"
                                   "border:0px;"
                                   "text-align: center;\n"
                                   "}\n"

                                   "#history::drop-down{\n"
                                   "image:url(images/arrowdown.png);\n"
                                   "width: 20px;\n"
                                   "height: 20px;\n"
                                   "text-align: center;\n"
                                   "}\n"

                                   "#history QAbstractItemView {\n"
                                   "background-color: rgb(255, 255, 255);\n"
                                   "outline: none;"
                                   "text-align: center;\n"

                                   "border:0px;"
                                   "\n"
                                   "}\n"

                                   "#history QAbstractItemView::item {\n"
                                   "background-color: #F4EBE6;\n"
                                   "color: #4A3B28;\n"
                                   "text-align: center;\n"
                                   "min-height: 35px; min-width: 50px;"
                                   "border:0px;"
                                   "}\n"

                                   "#history QListView{"
                                   "border:0px;"
                                   # "color:rgb(87, 96, 134);"
                                   # "background-color:rgb(255, 255, 255);"
                                   "font-weight:bold;"
                                   # "selection-background-color: rgb(47, 175, 178);"
                                   # "show-decoration-selected: 1;"
                                   "text-align: center;\n"
                                   "}"

                                   "#history QListView::item{"
                                   "border:0px;"
                                   "border-radius: 15px;"
                                   "padding:8px; "
                                   "margin:10px;"
                                   "text-align: center;\n"
                                   "}"

                                   "#history QListView::item:selected { "
                                   "color: white; "
                                   "background-color: #4A3B28}")
        self.history.setObjectName("history")
        self.horizontalLayout.addWidget(self.history)

        self.howtoUse = QtWidgets.QComboBox(self.threeBtn)
        # edited text allign
        self.howtoUse.setGeometry(200, 150, 150, 30)
        self.howtoUse.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.howtoUse.addItems(
            [
                "STEP 1: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                "STEP 2: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                "STEP 3: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",

            ])
        self.howtoUse.setEditable(True)
        self.ledit = self.howtoUse.lineEdit()
        self.ledit.setReadOnly(True)
        self.ledit.setAlignment(Qt.AlignCenter)
        self.howtoUse.setEditText("How to Use")

        def handleSelection(text):
            # change back to default title after item is selected
            self.howtoUse.setEditText("How to Use")

        self.howtoUse.activated[str].connect(handleSelection)
        # Disable showing the selected item in the title
        view = QListView()
        view.setMinimumSize(500, 200)
        view.setWordWrap(True)
        self.howtoUse.setView(view)
        self.howtoUse.setStyleSheet("#howtoUse{\n"
                                    "padding-left: 10px;\n"
                                    "border-radius:4px;\n"
                                    "font: 600 12pt \"Segoe UI\";\n"
                                    "color:#4A3B28;\n"
                                    "background: transparent;\n"
                                    "border:0px;"
                                    "text-align: center;\n"
                                    "}\n"

                                    "#howtoUse::drop-down{\n"
                                    "image:url(images/arrowdown.png);\n"
                                    "width: 20px;\n"
                                    "height: 20px;\n"
                                    "text-align: center;\n"
                                    "}\n"

                                    "#howtoUse QAbstractItemView {\n"
                                    "background-color: rgb(255, 255, 255);\n"
                                    "outline: none;"
                                    "text-align: center;\n"
                                    "border:0px;"
                                    "\n"
                                    "}\n"

                                    "#howtoUse QAbstractItemView::item {\n"
                                    "background-color: #F4EBE6;\n"
                                    "color: #4A3B28;\n"
                                    "text-align: center;\n"
                                    "min-height: 35px; min-width: 50px;"
                                    "border:0px;"

                                    "}\n"

                                    "#howtoUse QListView{"
                                    "border:0px;"
                                    # "color:rgb(87, 96, 134);"
                                    # "background-color:rgb(255, 255, 255);"
                                    "font-weight:bold;"

                                    # "selection-background-color: rgb(47, 175, 178);"
                                    # "show-decoration-selected: 1;"
                                    "text-align: left;\n"
                                    "}"

                                    "#howtoUse QListView::item{"
                                    "border:0px;"
                                    "border-radius: 15px;"
                                    "padding:8px; "
                                    "margin:10px;"
                                    "text-align: center;\n"
                                    "}"


                                    "#howtoUse QListView::item:selected { "
                                    "color: white; "
                                    "background-color: #4A3B28}")
        self.howtoUse.setObjectName("howtoUse")
        self.horizontalLayout.addWidget(self.howtoUse)

        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setGeometry(QtCore.QRect(210, 0, 481,100))
        self.widget_6.setStyleSheet("background-image: url(images/Crackterize.png);\n"
                                    "background-repeat: no-repeat; \n"
                                    "background-position: center;")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout.addWidget(self.widget_3)

        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.widgetUpload = QtWidgets.QWidget(self.widget_4)
        self.widgetUpload.setGeometry(QtCore.QRect(270, 0, 341, 120))
        effect = QtWidgets.QGraphicsDropShadowEffect()
        effect.setBlurRadius(8)
        self.widgetUpload.setGraphicsEffect(effect)
        self.widgetUpload.setStyleSheet("#widgetUpload{\n"
                                        "background-color: rgb(255, 255, 255);\n"
                                        "border-radius:28px;\n"
                                        "box-shadow: 55px 55px 150px black;\n"
                                        "}\n"
                                        "")
        self.widgetUpload.setObjectName("widgetUpload")


        # Upload Button
        self.uploadImg = QtWidgets.QPushButton("Upload Image",self.widgetUpload)
        # effect = QtWidgets.QGraphicsDropShadowEffect()
        # effect.setBlurRadius(8)
        # self.uploadImg.setGraphicsEffect(effect)
        self.uploadImg.setGeometry(QtCore.QRect(70, 30, 201, 41))
        self.uploadImg.setStyleSheet("#uploadImg{\n"
                                     "font-weight:bold;"
                                     "font-size:12px;"
                                     "color:white;"
                                     "background-color: rgb(144, 115, 87);\n"
                                     "border-top-left-radius :20px;"
                                     "border-top-right-radius : 20px; "
                                     "border-bottom-left-radius : 20px; "
                                     "border-bottom-right-radius : 20px;"
                                     "}\n"
                                     "#uploadImg:hover{\n"
                                     "color:rgb(144, 115, 87);"
                                     "border :3px solid rgb(144, 115, 87);"
                                     "background-color: rgb(255, 255, 255);\n"
                                     "}\n")
        self.uploadImg.setObjectName("uploadImg")

        self.textEdit = QtWidgets.QLabel("or create a new project",self.widgetUpload)
        self.textEdit.setGeometry(QtCore.QRect(110, 80, 161, 21))
        self.textEdit.setStyleSheet("#textEdit{\n"
                                     "font-weight:bold;"
                                     "color:#363131;"
                                     "}\n")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.widget_4)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
