# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select-category.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(718, 618)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("#widget{\n"
                                  "background-color: #FDF3e9\n"
                                  ";}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(40, -1, 40, 40)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setStyleSheet("#label{\n"
                                 "font-size: 30px;\n"
                                 "color: rgba(111, 75, 39, 0.77);\n"
                                 "font-weight: bold;}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 450))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 450))
        self.widget_2.setStyleSheet("background-color: rgba(76,146,215,255);\n"
                                    "border-radius: 30px;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("background-color: white;\n"
                                    "border-radius: 30px;\n"
                                    "")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_4)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet("#scrollArea {\n"
                                      "background-color: #F4EBE6;\n"
                                      "    border-top-left-radius: 10px;\n"
                                      "    border-bottom-left-radius: 10px;\n"
                                      "    border-top-right-radius: 10px;\n"
                                      "    border-bottom-right-radius: 10px;\n"
                                      "}\n"
                                      "\n"
                                      "#scrollArea QScrollBar:vertical {\n"
                                      "    background-color: #c3c3c3;\n"
                                      "    width: 15px;\n"
                                      "    margin: 15px 3px 15px 3px;\n"
                                      "    border: 1px transparent #2A2929;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "\n"
                                      "#scrollArea QScrollBar:vertical:hover {\n"
                                      "    width: 20px;\n"
                                      "}\n"
                                      "\n"
                                      "#scrollArea QScrollBar::handle:vertical {\n"
                                      "    background-color: #8c8c8c;\n"
                                      "    min-height: 5px;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "\n"
                                      "#scrollArea QScrollBar::sub-line:vertical {\n"
                                      "    margin: 3px 0px 3px 0px;\n"
                                      "    border-image: url(:/images/up_arrow_disabled.png);\n"
                                      "    height: 10px;\n"
                                      "    width: 10px;\n"
                                      "    subcontrol-position: top;\n"
                                      "    subcontrol-origin: margin;\n"
                                      "}\n"
                                      "\n"
                                      "#scrollArea QScrollBar::add-line:vertical {\n"
                                      "    margin: 3px 0px 3px 0px;\n"
                                      "    border-image: url(:/images/down_arrow_disabled.png);\n"
                                      "    height: 10px;\n"
                                      "    width: 10px;\n"
                                      "    subcontrol-position: bottom;\n"
                                      "    subcontrol-origin: margin;\n"
                                      "}\n"
                                      "\n"
                                      "#scrollArea QScrollBar::up-arrow:vertical,\n"
                                      "#scrollArea QScrollBar::down-arrow:vertical {\n"
                                      "    background: none;\n"
                                      "}\n"
                                      "\n"
                                      "#scrollArea QScrollBar::add-page:vertical,\n"
                                      "#scrollArea QScrollBar::sub-page:vertical {\n"
                                      "    background: none;\n"
                                      "}\n"
                                      "")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -56, 417, 488))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget_8)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setStyleSheet("#label_3{\n"
                                   "font-size: 18px;\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "font-weight: bold;}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.projects_wdgt = QtWidgets.QWidget(self.widget_8)
        self.projects_wdgt.setMinimumSize(QtCore.QSize(0, 0))
        self.projects_wdgt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.projects_wdgt.setObjectName("projects_wdgt")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.projects_wdgt)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.project_chb_widget = QtWidgets.QWidget(self.projects_wdgt)
        self.project_chb_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.project_chb_widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.project_chb_widget.setObjectName("project_chb_widget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.project_chb_widget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.project_chb = QtWidgets.QCheckBox(self.project_chb_widget)
        self.project_chb.setMinimumSize(QtCore.QSize(0, 30))
        self.project_chb.setStyleSheet("#project_chb {border : 1px solid rgba(76,146,215,255);\n"
                                       "border-radius :15px;\n"
                                       "color:black;\n"
                                       "font-size:13px;\n"
                                       "}\n"
                                       "#project_chb::indicator{border : 2px solid rgba(76,146,215,255);\n"
                                       "width : 16px;\n"
                                       "height : 16px;\n"
                                       "border-radius :10px;\n"
                                       "margin-left:5px;}\n"
                                       "#project_chb::indicator:checked {\n"
                                       "background-color: rgba(76,146,215,255);\n"
                                       "}\n"
                                       "")
        self.project_chb.setTristate(False)
        self.project_chb.setObjectName("project_chb")
        self.horizontalLayout_12.addWidget(self.project_chb)
        self.verticalLayout_8.addWidget(self.project_chb_widget)
        self.verticalLayout_5.addWidget(self.projects_wdgt)
        self.verticalLayout_4.addWidget(self.widget_8)
        self.folders_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.folders_widget.setObjectName("folders_widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.folders_widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_20 = QtWidgets.QWidget(self.folders_widget)
        self.widget_20.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_20.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.widget_20)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_4.setStyleSheet("#label_4{\n"
                                   "font-size: 18px;\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "font-weight: bold;\n"
                                   "border-right:1px solid grey;\n"
                                   "}")
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.select_all_fold = QtWidgets.QPushButton(self.widget_20)
        self.select_all_fold.setMaximumSize(QtCore.QSize(50, 16777215))
        self.select_all_fold.setStyleSheet("#select_all_fold{color: rgba(76,146,215,255);}\n"
                                           "#select_all_fold::hover{border-bottom:1px solid  rgba(76,146,215,255);;}\n"
                                           "")
        self.select_all_fold.setFlat(True)
        self.select_all_fold.setObjectName("select_all_fold")
        self.horizontalLayout_10.addWidget(self.select_all_fold)
        self.label_11 = QtWidgets.QLabel(self.widget_20)
        self.label_11.setMinimumSize(QtCore.QSize(10, 0))
        self.label_11.setMaximumSize(QtCore.QSize(10, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgba(76,146,215,255);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.clear_all_fold = QtWidgets.QPushButton(self.widget_20)
        self.clear_all_fold.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clear_all_fold.setStyleSheet("#clear_all_fold{color: rgba(76,146,215,255);}\n"
                                          "#clear_all_fold::hover{border-bottom:1px solid  rgba(76,146,215,255);;}\n"
                                          "")
        self.clear_all_fold.setFlat(True)
        self.clear_all_fold.setObjectName("clear_all_fold")
        self.horizontalLayout_10.addWidget(self.clear_all_fold)
        self.widget_24 = QtWidgets.QWidget(self.widget_20)
        self.widget_24.setObjectName("widget_24")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_24)
        self.horizontalLayout_13.setSpacing(20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_10.addWidget(self.widget_24)
        self.verticalLayout_6.addWidget(self.widget_20)
        self.widget_fo = QtWidgets.QWidget(self.folders_widget)
        self.widget_fo.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_fo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_fo.setObjectName("widget_fo")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_fo)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.folder_chb_widget = QtWidgets.QWidget(self.widget_fo)
        self.folder_chb_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.folder_chb_widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.folder_chb_widget.setObjectName("folder_chb_widget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.folder_chb_widget)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(10)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.folder_chb = QtWidgets.QCheckBox(self.folder_chb_widget)
        self.folder_chb.setMinimumSize(QtCore.QSize(0, 30))
        self.folder_chb.setStyleSheet("#folder_chb {border : 1px solid rgba(76,146,215,255);\n"
                                      "border-radius :15px;\n"
                                      "color:black;\n"
                                      "font-size:13px;}\n"
                                      "#folder_chb::indicator{border : 2px solid rgba(76,146,215,255);\n"
                                      "width : 16px;\n"
                                      "height : 16px;\n"
                                      "border-radius :10px;\n"
                                      "margin-left:5px;}\n"
                                      "#folder_chb::indicator:checked {\n"
                                      "background-color: rgba(76,146,215,255);\n"
                                      "}\n"
                                      "")
        self.folder_chb.setTristate(False)
        self.folder_chb.setObjectName("folder_chb")
        self.horizontalLayout_16.addWidget(self.folder_chb)
        self.verticalLayout_12.addWidget(self.folder_chb_widget)
        self.verticalLayout_6.addWidget(self.widget_fo)
        self.verticalLayout_4.addWidget(self.folders_widget)
        self.non_crack_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.non_crack_widget.setObjectName("non_crack_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.non_crack_widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_22 = QtWidgets.QWidget(self.non_crack_widget)
        self.widget_22.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_22.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.widget_22)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setStyleSheet("#label_5{\n"
                                   "font-size: 18px;\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "font-weight: bold;\n"
                                   "border-right:1px solid grey;\n"
                                   "}")
        self.label_5.setScaledContents(True)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.select_all = QtWidgets.QPushButton(self.widget_22)
        self.select_all.setMaximumSize(QtCore.QSize(50, 16777215))
        self.select_all.setStyleSheet("#select_all{color: rgba(76,146,215,255);}\n"
                                      "#select_all::hover{border-bottom:1px solid  rgba(76,146,215,255);;}\n"
                                      "")
        self.select_all.setFlat(True)
        self.select_all.setObjectName("select_all")
        self.horizontalLayout_11.addWidget(self.select_all)
        self.label_17 = QtWidgets.QLabel(self.widget_22)
        self.label_17.setMinimumSize(QtCore.QSize(10, 0))
        self.label_17.setMaximumSize(QtCore.QSize(10, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgba(76,146,215,255);")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_11.addWidget(self.label_17)
        self.clear_all = QtWidgets.QPushButton(self.widget_22)
        self.clear_all.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clear_all.setStyleSheet("#clear_all{color: rgba(76,146,215,255);}\n"
                                     "#clear_all::hover{border-bottom:1px solid  rgba(76,146,215,255);;}\n"
                                     "")
        self.clear_all.setFlat(True)
        self.clear_all.setObjectName("clear_all")
        self.horizontalLayout_11.addWidget(self.clear_all)
        self.verticalLayout_7.addWidget(self.widget_22)
        self.non_crack_2nd_widget = QtWidgets.QWidget(self.non_crack_widget)
        self.non_crack_2nd_widget.setMinimumSize(QtCore.QSize(0, 40))
        self.non_crack_2nd_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.non_crack_2nd_widget.setObjectName("non_crack_2nd_widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.non_crack_2nd_widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.non_crack_chb_widget = QtWidgets.QWidget(self.non_crack_2nd_widget)
        self.non_crack_chb_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.non_crack_chb_widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.non_crack_chb_widget.setObjectName("non_crack_chb_widget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.non_crack_chb_widget)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(10)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.non_crack_chb = QtWidgets.QCheckBox(self.non_crack_chb_widget)
        self.non_crack_chb.setMinimumSize(QtCore.QSize(0, 30))
        self.non_crack_chb.setStyleSheet("#non_crack_chb {border : 1px solid rgba(76,146,215,255);\n"
                                         "border-radius :15px;\n"
                                         "color:black;\n"
                                         "font-size:13px;}\n"
                                         "#non_crack_chb::indicator{border : 2px solid rgba(76,146,215,255);\n"
                                         "width : 16px;\n"
                                         "height : 16px;\n"
                                         "border-radius :10px;\n"
                                         "margin-left:5px;}\n"
                                         "#non_crack_chb::indicator:checked {\n"
                                         "background-color: rgba(76,146,215,255);\n"
                                         "}\n"
                                         "")
        self.non_crack_chb.setTristate(False)
        self.non_crack_chb.setObjectName("non_crack_chb")
        self.horizontalLayout_17.addWidget(self.non_crack_chb)
        self.horizontalLayout_5.addWidget(self.non_crack_chb_widget)
        self.verticalLayout_7.addWidget(self.non_crack_2nd_widget)
        self.verticalLayout_4.addWidget(self.non_crack_widget)
        self.crack_loc_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.crack_loc_widget.setObjectName("crack_loc_widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.crack_loc_widget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_23 = QtWidgets.QWidget(self.crack_loc_widget)
        self.widget_23.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_23.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_6 = QtWidgets.QLabel(self.widget_23)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setStyleSheet("#label_6{\n"
                                   "font-size: 18px;\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "font-weight: bold;\n"
                                   "border-right:1px solid grey;\n"
                                   "}")
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_18.addWidget(self.label_6)
        self.select_all_loc = QtWidgets.QPushButton(self.widget_23)
        self.select_all_loc.setMaximumSize(QtCore.QSize(50, 16777215))
        self.select_all_loc.setStyleSheet("#select_all_loc{color: rgba(76,146,215,255);}\n"
                                          "#select_all_loc::hover{border-bottom:1px solid  rgba(76,146,215,255);;}\n"
                                          "")
        self.select_all_loc.setFlat(True)
        self.select_all_loc.setObjectName("select_all_loc")
        self.horizontalLayout_18.addWidget(self.select_all_loc)
        self.label_20 = QtWidgets.QLabel(self.widget_23)
        self.label_20.setMinimumSize(QtCore.QSize(10, 0))
        self.label_20.setMaximumSize(QtCore.QSize(10, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgba(76,146,215,255);")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_18.addWidget(self.label_20)
        self.clear_all_loc = QtWidgets.QPushButton(self.widget_23)
        self.clear_all_loc.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clear_all_loc.setStyleSheet("#clear_all_loc{color: rgba(76,146,215,255);}\n"
                                         "#clear_all_loc::hover{border-bottom:1px solid  rgba(76,146,215,255);;}\n"
                                         "")
        self.clear_all_loc.setFlat(True)
        self.clear_all_loc.setObjectName("clear_all_loc")
        self.horizontalLayout_18.addWidget(self.clear_all_loc)
        self.widget_12 = QtWidgets.QWidget(self.widget_23)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_18.addWidget(self.widget_12)
        self.verticalLayout_9.addWidget(self.widget_23)
        self.crack_loc_2nd_widget = QtWidgets.QWidget(self.crack_loc_widget)
        self.crack_loc_2nd_widget.setMinimumSize(QtCore.QSize(0, 40))
        self.crack_loc_2nd_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.crack_loc_2nd_widget.setObjectName("crack_loc_2nd_widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.crack_loc_2nd_widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.crack_loc_chb_widget = QtWidgets.QWidget(self.crack_loc_2nd_widget)
        self.crack_loc_chb_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.crack_loc_chb_widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.crack_loc_chb_widget.setObjectName("crack_loc_chb_widget")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.crack_loc_chb_widget)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(10)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.crack_loc_chb = QtWidgets.QCheckBox(self.crack_loc_chb_widget)
        self.crack_loc_chb.setMinimumSize(QtCore.QSize(0, 30))
        self.crack_loc_chb.setStyleSheet("#crack_loc_chb {border : 1px solid rgba(76,146,215,255);\n"
                                         "border-radius :15px;\n"
                                         "color:black;\n"
                                         "font-size:13px;}\n"
                                         "#crack_loc_chb::indicator{border : 2px solid rgba(76,146,215,255);\n"
                                         "width : 16px;\n"
                                         "height : 16px;\n"
                                         "border-radius :10px;\n"
                                         "margin-left:5px;}\n"
                                         "#crack_loc_chb::indicator:checked {\n"
                                         "background-color: rgba(76,146,215,255);\n"
                                         "}\n"
                                         "")
        self.crack_loc_chb.setTristate(False)
        self.crack_loc_chb.setObjectName("crack_loc_chb")
        self.horizontalLayout_19.addWidget(self.crack_loc_chb)
        self.horizontalLayout_6.addWidget(self.crack_loc_chb_widget)
        self.verticalLayout_9.addWidget(self.crack_loc_2nd_widget)
        self.verticalLayout_4.addWidget(self.crack_loc_widget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.scrollArea)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMinimumSize(QtCore.QSize(160, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(160, 16777215))
        self.widget_5.setStyleSheet("background-color: rgba(76,146,215,255);")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setMinimumSize(QtCore.QSize(0, 210))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 210))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/icons8-print-96.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.print_btn = QtWidgets.QPushButton(self.widget_7)
        self.print_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.print_btn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.print_btn.setStyleSheet("#print_btn{\n"
                                     "background: white;\n"
                                     "font-weight:bold;\n"
                                     "color: #2E74A9;\n"
                                     "border-radius: 15px;\n"
                                     "font-family: Inter;\n"
                                     "}\n"
                                     "\n"
                                     "\n"
                                     "#print_btn::hover{\n"
                                     "color: #2E74A9;\n"
                                     "border : 3px solid  #2E74A9;\n"
                                     "background-color: white;\n"
                                     "}\n"
                                     "")
        self.print_btn.setObjectName("print_btn")
        self.verticalLayout_3.addWidget(self.print_btn)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_2.addWidget(self.widget_6)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Select Category"))
        self.label_3.setText(_translate("Dialog", "  Projects"))
        self.project_chb.setText(_translate("Dialog", "CheckBox"))
        self.label_4.setText(_translate("Dialog", " Folders"))
        self.select_all_fold.setText(_translate("Dialog", "Select All"))
        self.label_11.setText(_translate("Dialog", "∘"))
        self.clear_all_fold.setText(_translate("Dialog", "Clear all"))
        self.folder_chb.setText(_translate("Dialog", "CheckBox"))
        self.label_5.setText(_translate("Dialog", " Crack Inclusion / Exclusion"))
        self.select_all.setText(_translate("Dialog", "Select All"))
        self.label_17.setText(_translate("Dialog", "∘"))
        self.clear_all.setText(_translate("Dialog", "Clear all"))
        self.non_crack_chb.setText(_translate("Dialog", "CheckBox"))
        self.label_6.setText(_translate("Dialog", " Crack Location"))
        self.select_all_loc.setText(_translate("Dialog", "Select All"))
        self.label_20.setText(_translate("Dialog", "∘"))
        self.clear_all_loc.setText(_translate("Dialog", "Clear all"))
        self.crack_loc_chb.setText(_translate("Dialog", "CheckBox"))
        self.print_btn.setText(_translate("Dialog", "Print"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
