# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(372, 398)
        Dialog.setStyleSheet("#Dialog{background:rgb(255, 255, 255)}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_6 = QtWidgets.QWidget(Dialog)
        self.widget_6.setMinimumSize(QtCore.QSize(280, 0))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.concretecracked_2 = QtWidgets.QLabel(self.widget_6)
        self.concretecracked_2.setStyleSheet("#concretecracked_2{\n"
                                             "    \n"
                                             "color: #2E74A9;\n"
                                             "font: bold;\n"
                                             "border: 2px solid white;\n"
                                             "font-size: 20px;\n"
                                             "border-bottom-color: rgb(172, 172, 172);\n"
                                             "}")
        self.concretecracked_2.setAlignment(QtCore.Qt.AlignCenter)
        self.concretecracked_2.setWordWrap(True)
        self.concretecracked_2.setObjectName("concretecracked_2")
        self.verticalLayout_2.addWidget(self.concretecracked_2)
        self.widget_10 = QtWidgets.QWidget(self.widget_6)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.widget_10)
        self.label_2.setStyleSheet("#label_2{\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "font-size: 13px;\n"
                                   "font-weight: bold;\n"
                                   "}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.location_label = QtWidgets.QLabel(self.widget_10)
        self.location_label.setMinimumSize(QtCore.QSize(134, 0))
        self.location_label.setMaximumSize(QtCore.QSize(134, 16777215))
        self.location_label.setStyleSheet("#location_label{\n"
                                          "    color:  #555555;\n"
                                          "font: bold;\n"
                                          "    font-size: 15px}")
        self.location_label.setAlignment(QtCore.Qt.AlignCenter)
        self.location_label.setWordWrap(True)
        self.location_label.setObjectName("location_label")
        self.horizontalLayout_10.addWidget(self.location_label)
        self.verticalLayout_2.addWidget(self.widget_10)
        self.widget_13 = QtWidgets.QWidget(self.widget_6)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.widget_13)
        self.label_3.setStyleSheet("#label_3{\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "font-size: 13px;\n"
                                   "font-weight: bold;\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.type_label = QtWidgets.QLabel(self.widget_13)
        self.type_label.setMinimumSize(QtCore.QSize(134, 0))
        self.type_label.setMaximumSize(QtCore.QSize(134, 16777215))
        self.type_label.setStyleSheet("#type_label{\n"
                                      "    color:  #555555;\n"
                                      "font: bold;\n"
                                      "    font-size: 15px;\n"
                                      "}")
        self.type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.type_label.setWordWrap(True)
        self.type_label.setObjectName("type_label")
        self.horizontalLayout_11.addWidget(self.type_label)
        self.verticalLayout_2.addWidget(self.widget_13)
        self.widget_11 = QtWidgets.QWidget(self.widget_6)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widgetPosition = QtWidgets.QLabel(self.widget_11)
        self.widgetPosition.setStyleSheet("#widgetPosition{\n"
                                          "color: rgba(111, 75, 39, 0.77);\n"
                                          "font-size: 13px;\n"
                                          "font-weight: bold;\n"
                                          "}")
        self.widgetPosition.setObjectName("widgetPosition")
        self.horizontalLayout_13.addWidget(self.widgetPosition)
        self.prog_label = QtWidgets.QLabel(self.widget_11)
        self.prog_label.setMinimumSize(QtCore.QSize(134, 0))
        self.prog_label.setMaximumSize(QtCore.QSize(134, 16777215))
        self.prog_label.setStyleSheet("#prog_label{\n"
                                      "    color:  #555555;\n"
                                      "font: bold;\n"
                                      "    font-size: 15px;\n"
                                      "}")
        self.prog_label.setAlignment(QtCore.Qt.AlignCenter)
        self.prog_label.setWordWrap(True)
        self.prog_label.setObjectName("prog_label")
        self.horizontalLayout_13.addWidget(self.prog_label)
        self.verticalLayout_2.addWidget(self.widget_11)
        self.widget_12 = QtWidgets.QWidget(self.widget_6)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.widget_12)
        self.label_4.setStyleSheet("#label_4{\n"
                                   "color: rgba(111, 75, 39, 0.77);\n"
                                   "font-size: 13px;\n"
                                   "font-weight: bold;\n"
                                   "}")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.date_added = QtWidgets.QLabel(self.widget_12)
        self.date_added.setMinimumSize(QtCore.QSize(134, 0))
        self.date_added.setMaximumSize(QtCore.QSize(134, 16777215))
        self.date_added.setStyleSheet("#date_added{\n"
                                      "    color:  #555555;\n"
                                      "font: bold;\n"
                                      "    font-size: 15px}")
        self.date_added.setAlignment(QtCore.Qt.AlignCenter)
        self.date_added.setWordWrap(True)
        self.date_added.setObjectName("date_added")
        self.horizontalLayout_12.addWidget(self.date_added)
        self.verticalLayout_2.addWidget(self.widget_12)
        self.widget_15 = QtWidgets.QWidget(self.widget_6)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.widget_15)
        self.widget.setStyleSheet("#widget{\n"
                                  "    \n"
                                  "border: 2px solid white;\n"
                                  "border-bottom-color: rgb(172, 172, 172);;\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widgetPos_2 = QtWidgets.QLabel(self.widget)
        self.widgetPos_2.setMinimumSize(QtCore.QSize(180, 0))
        self.widgetPos_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.widgetPos_2.setStyleSheet("#widgetPos_2{\n"
                                       "color: rgba(111, 75, 39, 0.77);\n"
                                       "font-size: 13px;\n"
                                       "font-weight: bold;\n"
                                       "}")
        self.widgetPos_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.widgetPos_2.setWordWrap(True)
        self.widgetPos_2.setObjectName("widgetPos_2")
        self.horizontalLayout_2.addWidget(self.widgetPos_2)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.edit_remarks = QtWidgets.QPushButton(self.widget)
        self.edit_remarks.setMinimumSize(QtCore.QSize(25, 25))
        self.edit_remarks.setMaximumSize(QtCore.QSize(25, 25))
        self.edit_remarks.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_remarks.setIcon(icon)
        self.edit_remarks.setIconSize(QtCore.QSize(20, 25))
        self.edit_remarks.setFlat(True)
        self.edit_remarks.setObjectName("edit_remarks")
        self.horizontalLayout_2.addWidget(self.edit_remarks)
        self.verticalLayout_3.addWidget(self.widget)
        self.remarks = QtWidgets.QLabel(self.widget_15)
        self.remarks.setMinimumSize(QtCore.QSize(0, 50))
        self.remarks.setMaximumSize(QtCore.QSize(16777215, 50))
        self.remarks.setStyleSheet("#remarks{\n"
                                   "    color:  #555555;\n"
                                   "font: bold;\n"
                                   "    font-size: 15px;\n"
                                   "}")
        self.remarks.setTextFormat(QtCore.Qt.RichText)
        self.remarks.setScaledContents(True)
        self.remarks.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.remarks.setWordWrap(True)
        self.remarks.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
        self.remarks.setObjectName("remarks")
        self.verticalLayout_3.addWidget(self.remarks)
        self.verticalLayout_2.addWidget(self.widget_15)
        self.widget_3 = QtWidgets.QWidget(self.widget_6)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.savebtn = QtWidgets.QPushButton(self.widget_3)
        self.savebtn.setMinimumSize(QtCore.QSize(0, 35))
        self.savebtn.setMaximumSize(QtCore.QSize(16777215, 35))
        self.savebtn.setStyleSheet("#savebtn{\n"
                                   "background: #2E74A9;\n"
                                   "font-weight:bold;\n"
                                   "color: white;\n"
                                   "border-radius: 7px;\n"
                                   "font-family: Inter;\n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "#savebtn::hover{\n"
                                   "color: #2E74A9;\n"
                                   "border : 3px solid  #2E74A9;\n"
                                   "background-color: white;\n"
                                   "}\n"
                                   "")
        self.savebtn.setObjectName("savebtn")
        self.horizontalLayout_5.addWidget(self.savebtn)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.concretecracked_2.setText(_translate("Dialog", "Details:"))
        self.label_2.setText(_translate("Dialog", "Location of Crack:"))
        self.location_label.setText(_translate("Dialog", "609.5 mm"))
        self.label_3.setText(_translate("Dialog", "Crack Type:"))
        self.type_label.setText(_translate("Dialog", "50.91 mm"))
        self.widgetPosition.setText(_translate("Dialog", "Crack Progression:"))
        self.prog_label.setText(_translate("Dialog", "Horizontal"))
        self.label_4.setText(_translate("Dialog", "Date Added:"))
        self.date_added.setText(_translate("Dialog", "609.5 mm"))
        self.widgetPos_2.setText(_translate("Dialog", "Remarks:"))
        self.remarks.setText(_translate("Dialog", "safasfasdada"))
        self.savebtn.setText(_translate("Dialog", "Okay"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
